### ISSUE TITLE
Merge in FSGP changes

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Telemetry-Server#146]
Figure out which changes can be:

- Merged to master or Race Optimization (PRs as needed)

- Placed on a new branch for work to continue

**Comment by Reddragoneer1** [comment]
We need to confirm with electrical the accuracy of our calculations, but if they're good then,

RaceOptimization:
Everything except labels

Separate branches: 
Labels
Excel exporting

**Comment by bill-luu** [comment]
I think the only thing that was wrong was our distance calculation. Let's make that a separate issue.

**Comment by Reddragoneer1** [comment]
RaceOptimization has been merged
