### ISSUE TITLE
Trigger Side Panels to Disappear Dependent on Screen Size

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Telemetry-Server#43]
When the screen width is too small, the site should disappear the side panels and just have the main program.

**Comment by Reddragoneer1** [comment]
Looks good to me. Should we try and put it on the IP address to see if it works on our phones?

**Comment by Reddragoneer1** [comment]
Panel disappearing looks good on mobile, we just need to make the rest scalable with mobile size
