### ISSUE TITLE
Min & Max Cell Voltage incorrect rounding 

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Telemetry-Server#65]
The min and max cell voltage needs to be divided by 1000.

**Comment by Reddragoneer1** [comment]
Which page is the min and max cell voltage on? Battery, Motor, MPPT, or right side panel?

**Comment by bill-luu** [comment]
Battery & the side panel

**Comment by bill-luu** [comment]
My b, it's actually called Low and High cell voltage

**Comment by Reddragoneer1** [comment]
How come we're dividing it here instead of when the data is initially sent?
