### ISSUE TITLE
Populate Data

### ISSUE THREAD

**Issue by Reddragoneer1** [UCSolarCarTeam/Epsilon-Telemetry-Server#95]
New row for lap data
Lap No. | Lap Time | Total Power In | Total Power Out | Distance

**Comment by bill-luu** [comment]
https://docs.google.com/document/d/1Xl1AD5aZjhMhxXJ7C4tibxoxULANoSatnQI9HWPXwEY/edit?usp=sharing

Calculations Doc

**Comment by Mavestri** [comment]
@bill-luu Think this issue can be closed off with #134 closed
